import time
import os
import sys
import random
import phonenumbers
from phonenumbers import geocoder
from phonenumbers import carrier

#import pyshorteners
#from pyshorteners import shorteners

#from  string import panctuation
#colour
red = '\033[31m'
yellow = '\033[93m'
green = '\033[92m'
clear = '\033[0m'
bold = '\033[01m'
cyan = '\033[96m'
cy='\033[095m'
cya='\033[035m'

# Set color
R = '\033[31m' # Red
N = '\033[1;37m' # White
G = '\033[32m' # Green
O = '\033[0;33m' # Orange
B = '\033[1;34m' #Blue
Y = '\033[93m'
os.system("clear")
time.sleep(2)
os.system("clear")
os.system("figlet amlike")
print("")

print(R+"THIS TOOL IS CODED BY AMLIKE YOU MAY SUPPORT HIS PROJECT BY DONATING HIM SOME MONEY THROUGH THIS NUMBER 0679859446 \n SUPPORT YOUNG TANZANIAN DEVELOPER SO AS TO FASTER OUR TECHNOLOGY IN GENERAL.")
print("")
print("")
print("")
print("")
print(cya+"SUPPORT YOUR LOCAL DEVELOPER")

time.sleep(15)
os.system("clear")
time.sleep(2)
os.system("figlet Amlike")
time.sleep(1)
print(R+"  Tool name:Team AmlikeTz-Spear")
                                    
print(B+ "\t\t Developer: AmlikeTz")
print("")
print(B+"[01]:Password Generator")
print("")
print(Y+"[02]:Amlike URL Shortner")
print("")
print(G+"[03]:Phone Number Scan")
print("")
print(R+"[0]:Update Tool")
print("")
print("")
time.sleep(1)
for i in range(100):
  pasi = open("Password.txt", "w")
  am=input(B+"[*]Enter your choice: ")
  if am=="01":
     import random
     from string import digits
     from string import ascii_letters
     os.system("clear")
     time.sleep(1)                                                                                          
     os.system("figlet AmlikeTz")
     print(B+ "\t Developer: AmlikeTz")
     print("")
     print(R+"{01}: Four(04) Digit Password")
     print("")
     print(O+"{02}: Six(06) Digit Password")
     print("")
     print(G+"{03}: Eight(08) Digit Password")
     print("")
     print(B+"{04}: Ten(10) Digit Password")
     print("")
     for i in range(180):
       dr=input(N+"[*]Enter your choice✓:")
       if dr=="01":
           os.system("clear")
           os.system("figlet 4-Digit")
           print("")
           print(R+"\t\tCoded by: Amlike")
           print("")
           print("")
           name = input(B+"Enter your name: ")
           print("")
           num = input("please choose any sign to include in your password™✓""\n Becouse This will help ur passcode To be more Sucure From Hackers""\n Example:&,$,!,@'#.""\n [*]Enter ur Sign here: ")
           print("")
           print("")
           user = name + num
           symbols = ascii_letters + digits
           secure_random = random.SystemRandom()
           password = "".join(secure_random.choice(symbols + user)
                             for i in range(4))

           os.system("clear")
           time.sleep(2)
           print("")
           os.system("figlet password")
           print("")
           print("")
           print(N+"[*]PLEASE WAIT...***")
           print("")
           print(R+"[*]CREATING YOUR PASSWORD™✓✓")
           print("")
           time.sleep(5)
           print("")
           print(O+"YOUR SAVED PASSWORD IS SUCCESSFUL CREATED AS: ")
           print("👇👇👇👇")
           print("")
           print("")
           print(password)
           print("")
           print("™™✓✓✓✓ ")
           time.sleep(2)
           print(Y+"GO TO YOUR TERMINAL TYPE ls and Then nano Password.txt To view Your Saved Password.Note once you forget this Password u can view it from ur terminal")
           print("")
           print("")
           time.sleep(25)
           print(password, file = pasi)

           print("")
           print("")
       elif dr=="02":
           os.system("clear")
           os.system("figlet 6-DIGIT")
           print(R+"\t\tCoded by: Amlike")
           print("")
           print("")
           name = input(B+"Enter your name: ")
           print("")
           num = input("please choose any sign to include in your password™✓""\n Becouse This will help ur passcode To be more Sucure From Hackers""\n Example:&,$,!,@'#.""\n [*]Enter ur Sign here: ")
           print("")
           print("")
           user = name + num
           symbols = ascii_letters + digits
           secure_random = random.SystemRandom()
           password = "".join(secure_random.choice(symbols + user)
                              for i in range(6))

           os.system("clear")
           time.sleep(2)
           print("")
           os.system("figlet password")
           print("")
           print("")
           print(N+"[*]PLEASE WAIT...***")
           print("")
           print(R+"[*]CREATING YOUR PASSWORD™✓✓")
           print("")
           time.sleep(5)
           print("")
           print(O+"YOUR SAVED PASSWORD IS SUCCESSFUL CREATED AS: ")
           print("👇👇👇👇")
           print("")
           print(password)
           print("")
           print("™™✓✓✓✓ ")
           time.sleep(2)
           print(Y+"GO TO YOUR TERMINAL TYPE ls and Then nano Password.txt To view Your Saved Password.Note once you forget this Password u can view it from ur terminal")
           print("")
           print("")
           time.sleep(25)
           print(password, file = pasi)

           print("")
           print("")
           print("")
           print("")

       elif dr=="03":
           os.system("clear")
           os.system("figlet 8-DIGIT")
           print("")
           print(R+"\t\tCoded by: Amlike")
           print("")
           print("")
           name = input(B+"Enter your name: ")
           print("")
           num = input("please choose any sign to include in your password™✓""\n Becouse This will help ur passcode To be more Sucure From Hackers""\n Example:&,$,!,@'#.""\n [*]Enter ur Sign here: ")
           print("")
           print("")
           user = name + num
           symbols = ascii_letters + digits
           secure_random = random.SystemRandom()
           password = "".join(secure_random.choice(symbols + user)
                              for i in range(8))
           os.system("clear")
           time.sleep(2)
           print("")
           os.system("figlet password")
           print("")
           print("")
           print(N+"[*]PLEASE WAIT...***")
           print("")
           print(R+"[*]CREATING YOUR PASSWORD™✓✓")
           print("")
           time.sleep(5)
           print("")
           print(O+"YOUR SAVED PASSWORD IS SUCCESSFUL CREATED AS: ")
           print("👇👇👇👇")
           print("")
           print(password)
           print("")
           print("")
           print("™™✓✓✓✓ ")
           time.sleep(2)
           print(Y+"GO TO YOUR TERMINAL TYPE ls and Then nano Password.txt To view Your Saved Password.Note once you forget this Password u can view it from ur terminal")
           print("")
           print("")
           time.sleep(25)
           print(password, file = pasi)

           print("")
           print("")
           print("")
       elif dr=="04":
           os.system("clear")
           time.sleep(2)
           os.system("figlet 10-Digit")
           print("")
           print(R+"\t\tCoded by: Amlike")
           print("")
           print("")
           name = input(B+"Enter your name: ")
           print("")
           num = input("please choose any sign to include in your password™✓""\n Becouse This will help ur passcode To be more Sucure From Hackers""\n Example:&,$,!,@'#.""\n [*]Enter ur Sign here: ")
           print("")
           print("")
           user = name + num
           symbols = ascii_letters + digits
           secure_random = random.SystemRandom()
           password = "".join(secure_random.choice(symbols + user)
                              for i in range(10))
           os.system("clear")
           time.sleep(2)
           print("")
           os.system("figlet password")
           print("")
           print("")
           print(N+"[*]PLEASE WAIT...***")
           print("")
           print(R+"[*]CREATING YOUR PASSWORD™✓✓")
           print("")
           time.sleep(5)
           print("")
           print(O+"YOUR SAVED PASSWORD IS SUCCESSFUL CREATED AS: ")
           print("👇👇👇👇")
           print("")
           print(password)
           print("")
           print("")
           print("™™✓✓✓✓ ")
           time.sleep(2)
           print(Y+"GO TO YOUR TERMINAL TYPE ls and Then nano Password.txt To view Your Saved Password.Note once you forget this Password u can view it from ur terminal")
           print("")
           print("")
           time.sleep(25)
           print(password, file = pasi)
           print("")
           print("")
           print("")
           sys.exit(1)
       else:
            os.system("clear")
            time.sleep(1)
            print("")
            print("")
            sys.exit(R+"CHAGUO LAKO SIO SAHIHI. TEAM AMLIKETZ-SPEAR IS GOING TO EXIT™✓✓✓ FROM YOUR TERMINAL.")
            time.sleep(4)
            print("")
  if am=="02":
        os.system("clear")
        time.sleep(2)
        print("")
        print("")
        print("PLEASE WAIT....")
        print("")
        time.sleep(1)
        os.system("clear")
        os.system("figlet Shortner")
        print(R+"\t\t  Coder:Amlike™✓✓")
        print("")
        print(B+"[01]: Amlike Bitly Link ")
        print("")
        print(Y+"[02]: Amlike Cutly Link")
        print("")
        for i in range(50):
          co=input(R+"{*}Enter Your choice: ")
          if co=="01":
             os.system("clear")
             time.sleep(2)
             os.system("figlet Amlike")
             print("")
             print(red+"\t\t  Coded by:Amlike")
             print("")
             link = input(green+"[*]Paste you link here: ")
             os.system("clear")
             time.sleep(2)
             os.system(" figlet UR-URL")
             print("")
             print("\t\t Developer: Amlike")
             print("")
             print(yellow+"Thank you for using This tool.Check out out  🙏👇👇👇 Ur Link✓✓")
             print("")
             print("")
#             print(pyshorteners.Shortner().clckru.short(link))
             print("")
             print(R+"HTTPError API UNDER MAINTAINANCE TRY NO 02 CUTTLY SHORTENER\n[™]SORRY FOR INCOVINIENCE")
             print("")
             print("")
          if co=="02":
             os.system("clear")
             os.system("figlet URL")
             print("\t\tCoded by:AmlikeTz")
             print("")
             print("")
             import requests
             api_key = "abd64eb9caaa0900479e0f864288a5cbcf116"
             # the URL you want to shorten
             url = input(G+"[•]Enter Your Link To Shorten: ")
             # preferred name in the URL
             api_url = f"https://cutt.ly/api/api.php?key={api_key}&short={url}"
             # or
             # api_url = f"https://cutt.ly/api/api.php?key={api_key}&short={url}&name=some_unique_name"
             # make the request
             os.system("clear")
             data = requests.get(api_url).json()["url"]
             if data["status"] == 7:
                 os.system("figlet UR-URL")
                 print("")
                 print("")
                 print(G+"Check Ur shortened Ur Down™✓✓✓")
                 print("")
                 print("")
                 # OK, get shortened URL
                 shortened_url = data["shortLink"]
                 print("Shortened URL:", shortened_url)
                 print("")
                 print("")
                 time.sleep(2)
                 print(cya+"SuCCESSFUL")
                 sys.exit(1)
             else:
                 print("[!] Error Shortening URL:")
                 print("")
                 print("")
                 time.sleep(1)
                 sys.exit(1)        

  elif am=="03":
         os.system("clear")
         time.sleep(2)
         os.system("figlet +NO.")
         print("\t\t  Coded by:Amlike")
         print("")
         time.sleep(1)
         print("")
         print(B+"Note:Start with Country code\n[•]Example:+255679767790✓✓")
         print("")

         print("")
         number=input(cya+"Enter Your Number To Scan: ")
         ch_nmber = phonenumbers.parse(number,"CH")
         service_nmber = phonenumbers.parse(number,"RO")
         print("")
         time.sleep(1)
         print((cya+"Your Victim Country:"),geocoder.description_for_number(ch_nmber,"en"))
         print("")
         time.sleep(1)              
         print("")
         print((G+"Your Victim ISP: "),carrier.name_for_number(service_nmber,"en"))
         print("")
         time.sleep(1)
         print(R+"    HTTPError Not Enogh Token To Perfom This or Buy Token to Amlike!!-;")
                                    
         print("")
         print(B+"Your Victim Region: ")
         print("")
         print("")
         time.sleep(1)
         print(G+"Your Victim Name:")
         time.sleep(1)
         print("")
         print("")
         print(Y+"Your Victim Phone:")
         print("")
         sys.exit("")

  elif am=="0":
         os.system("clear")
         time.sleep(2)
         print("")
         print("")
         print("PLEASE WAIT....")
         print("")
         time.sleep(1)
         print("YOUR TOOL IS NOW UPGRADING™✓✓✓✓")
         time.sleep(1)
         os.system("clear")
         os.system("rm -rf Team-AmlikeTzSpear;git clone https://github.com/Amlike-Tz/Team-AmlikeTzSpear.git")
         os.system("cd Team-AmlikeTzSpear;pip install -r requirements.txt")
         os.system("python AmSpear.py")

  else:
         os.system("clear")
         time.sleep(1)
         print("")
         print("")
         print(R+"CHAGUO LAKO SIO SAHIHI. TEAM AMLIKETZ-SPEAR IS GOING TO EXIT FROM YOUR TERMINAL")
         time.sleep(4)
         print("")
         sys.exit("")
         os.system("exit")
         sys.exit(1)
